[package]
name = "trunk-template"
version = "0.1.0"
edition = "2021"
description = "Template for starting a Yew project using Trunk"
readme = "README.md"
repository = "https://github.com/yewstack/yew-trunk-minimal-template"
license = "MIT OR Apache-2.0"
keywords = ["yew", "trunk"]
categories = ["gui", "wasm", "web-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
gloo = "0.8.0"
gloo-console = "0.2.3"
yew = { version="0.20", features=["csr"] }
web-sys = "0.3.61"

[dependencies.spaik]
git = "https://github.com/snyball/spaik.git"
default-features = false
features = ["no-threading"]

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = "z"
